### ISSUE TITLE
Attempting to cap the Admin gives a message but does not cap the user

### ISSUE THREAD

**Issue by Struckdown** [gojeffcho/megabot#1]
When a user tries to use the !cap command to cap the admin, a message displays that the user has been capped for attempting to cap the admin.
However, the user does not get the "capped" role.
The expected behaviour is that the user would receive the capped role, therefore being unable to send messages in any channels for the duration of the cap.

**Comment by gojeffcho** [comment]
Fixed in #e56a6c2 - the `add_role()` was not added to this case, and is now implemented.  Tested with @Struckdown and confirmed working.
