### ISSUE TITLE
!roll modifiers should be able to be added to the !roll command

### ISSUE THREAD

**Issue by Struckdown** [gojeffcho/megabot#2]
When a user uses the !roll command, it would be good to be able to add modifiers to add to the final result. Such as +3 or -2.

!roll 1d20+2
would be the ideal full usage. Stretch goal to incorporate multiple "+", and other math operations

A result of 18 would have the +2 added to it for a final result of 20.

**Comment by gojeffcho** [comment]
Completed in 5424947.
